batch_size: 64
batch_size_val: 16
crop_image: true
dataset: tless
full_eval: true
full_img: true
img_size:
- 224
- 224
learning_rate: 0.0001
mask: true
mlp_layers:
- 256
- 256
- 256
- 256
num_epochs: 10
num_fourier_comp: 1
num_train_iter: 200
num_train_queries: 4096
num_val_iter: 100
obj_id: '5'
occlusion: false
random_seed: 11
resnet_depth: 18
save_freq: 2
start_save: 2
train_mode: 2
warmup_steps: 20
