dataset: tabletop
icp_iteration: 1
length: 15000
material: false
max_iteration: 40
obj_id: 5
resolution:
- 1920
- 1080
skip: true
threshold:
- 100
- 20
- 2
verbose: false
voxel_size_global: 0.2
voxel_size_local: 0.2
conv_metric: rnc
l2_threshold: 0.1
global_dist_threshold: 0.8
