dataset: tabletop
icp_iteration: 1
length: 15000
material: true
max_iteration: 20
obj_id: 3
resolution:
- 1920
- 1080
skip: false
threshold:
- 100
- 20
- 2
verbose: false
voxel_size_global: 0.2
voxel_size_local: 0.2
conv_metric: rnc
l2_threshold: 5
global_dist_threshold: 0.8