dataset: tabletop
icp_iteration: 1
length: 20000
material: true
max_iteration: 40
obj_id: 4
resolution:
- 1920
- 1080
skip: false
threshold:
- 800
- 20
- 2
verbose: false
voxel_size_global: 0.2
voxel_size_local: 0.2
conv_metric: l2
l2_threshold: 0.1
global_dist_threshold: 0.8
